FROM paddlepaddle/paddle:2.4.2-gpu-cuda11.7-cudnn8.4-trt8.4
MAINTAINER lianshufeng <251708339@qq.com>

# 添加 依赖
Add ./ /docker

# 安装依赖 (cpu)
RUN pip install -r /docker/requirements-gpu.txt
RUN pip install --upgrade paddlehub
RUN bash /docker/script/install.sh

# 工作目录
WORKDIR /work

