version: "3"

services:
  paddlehub:
    image: lianshufeng/paddlehub
    volumes:
      - "./work:/work"
      - "./pip.conf:/root/.pip/pip.conf"
      - "./cache/paddlehub:/root/.paddlehub"
      - "./cache/paddlenlp:/root/.paddlenlp"
      - "./cache/python/dist-packages:/usr/local/lib/python3.7/dist-packages"
    ports:
      - "9999:8888"
    container_name: paddlehub
    # restart: always
    # command: bash ernie_zeus.sh
    # command: bash ernie_vilg.sh
    # command: bash ernie_gen_lover_words.sh
    # command: bash ernie_gen_acrostic_poetry.sh
    command: bash fastspeech2_baker.sh
    





    
    